//
// Created by bruno on 3/6/24.
//

#ifndef DA_WATERSUPPLYMANAGEMENT_WATERSUPPLYNETWORK_H
#define DA_WATERSUPPLYMANAGEMENT_WATERSUPPLYNETWORK_H


class WaterSupplyNetwork {

};


#endif //DA_WATERSUPPLYMANAGEMENT_WATERSUPPLYNETWORK_H
